formatter: "markdown table"

version: ""

header-from: main.tf
footer-from: ""

sections:
  hide: []
  show: []

content: |-
  # terraform-aws-amplify

  [![official JetBrains project](https://jb.gg/badges/official.svg)](https://confluence.jetbrains.com/display/ALL/JetBrains+on+GitHub)

  AWS Amplify is a development platform for building secure, scalable mobile and web
  applications. It offers a broad range of services and features, including
  authentication, analytics, API (GraphQL and REST), interactions, and more.
  Amplify simplifies the setup of new applications with a CLI interface, and it
  integrates with your version control system to enable continuous deployment.
  The service provides a unified model to manage backend and frontend development
  workflows, and it helps to seamlessly integrate with other AWS services.

  The terraform-aws-amplify module simplifies the deployment process of web site by automatically
  deploying the static website from an existing S3 bucket to a new AWS Amplify service that it sets up for you.

  ## Compatibility

  The minimum supported Terraform version is: 1.3.0.

  ## Repository organization

  * [examples](./examples): this folder contains ready to use examples that show how to use this Module;

  * [tests](./test): this folder contains a list of automated tests for this Module and examples;

  * [lib](./lib): this folder contains a list of local utilities, mostly Makefiles, to support the
    contributor's maintenance effort of this Module;

  * [modules](./modules): this folder contains a list of local Terraform modules that the Root Module uses;

  * [.github](./.github): this folder contains a list of GitHub workflows to support contributions
    during change requests and releases of this Module.

  ## Resources

  Documentation about the AWS Amplify service can be found [here](https://docs.aws.amazon.com/amplify/).

  ## Contribution guides

  Refer to this [page](./CONTRIBUTING.md) for details in regard to contribution instructions.

  {{ .Requirements }}
  {{ .Providers }}
  {{ .Resources }}
  {{ .Inputs }}
  {{ .Outputs }}

output:
  file: "README.md"
  mode: replace

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
